#!/usr/bin/env bash
# display username, user id and home directory for eac line of /etc/paswwd

input="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$input"
